name: mexico_elections_2024
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - geopandas
  - shapely
  - matplotlib
  - seaborn
  - scikit-learn
  - pyproj
  - jupyterlab
  - jupyter
  - notebook
  - gdal
  - seaborn
  - statsmodels
  - mapclassify
  - rasterio
  - folium
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pip
  - pip:
      - pyrolite
